name: Streamlit App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Test the app (but don't run it)
    - name: Lint and Test App
      run: |
        echo "Testing Streamlit app for errors"
        streamlit --version  # Test if Streamlit is installed correctly
        python -m py_compile app.py  # Check for syntax errors in app.py

    # Optional: You can also run other tests, like unit tests, here if you have them
